---

resources:
- name: concourse-app
  type: git
  source:
    uri: https://github.com/mandoz/concourse-tutorial

jobs:
- name: unit-test
  public: true
  serial: true
  plan:
  - get: concourse-app
    trigger: true

  - task: unit-test
    file: concourse-app/ci/tasks/test.yml
